services:
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:2024-10-14
    depends_on:
      lakekeeper:
        condition: service_healthy
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./spark/apps:/home/jovyan/examples/
    networks:
      - lakehouse-network
    ports:
      - "8888:8888"
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - lakehouse-network
    volumes:
      - minio-data:/data

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    restart: "no"
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc ls minio/bronze || /usr/bin/mc mb minio/bronze;
      /usr/bin/mc ls minio/silver || /usr/bin/mc mb minio/silver;
      /usr/bin/mc ls minio/gold || /usr/bin/mc mb minio/gold;
      echo 'Buckets initialized successfully';
      "
    networks:
      - lakehouse-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://shared-db:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_admin
      - KC_DB_PASSWORD=keycloak_password
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - ./keycloak/create-iceberg-admin.sh:/opt/keycloak/create-iceberg-admin.sh
      - ./keycloak/entrypoint.sh:/opt/keycloak/entrypoint.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'exec 3<>/dev/tcp/127.0.0.1/8080;echo -e "GET /realms/master/.well-known/openid-configuration HTTP/1.1\r\nhost: 127.0.0.1:8080\r\nConnection: close\r\n\r\n" >&3;grep "jwks_uri"  <&3',
        ]
      interval: 2s
      timeout: 10s
      retries: 2
      start_period: 60s
    depends_on:
      shared-db:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/opt/keycloak/entrypoint.sh"]
    ports:
      - "30080:8080"
    command:
      [
        "start-dev",
        "--metrics-enabled=true",
        "--health-enabled=true",
        "--import-realm",
        "--verbose",
        "--log-level=INFO",
        "--features=token-exchange",
      ]
    networks:
      - lakehouse-network

  lakekeeper:
    image: ${LAKEKEEPER_TEST__SERVER_IMAGE:-quay.io/lakekeeper/catalog:latest-main}
    container_name: lakekeeper
    pull_policy: always
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://lakekeeper_admin:lakekeeper_password@shared-db:5432/lakekeeper_db
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://lakekeeper_admin:lakekeeper_password@shared-db:5432/lakekeeper_db
      - LAKEKEEPER__AUTHZ_BACKEND=openfga
      - LAKEKEEPER__OPENFGA__ENDPOINT=http://openfga:8081
      - LAKEKEEPER__OPENID_PROVIDER_URI=http://keycloak:8080/realms/iceberg
      - LAKEKEEPER__OPENID_ADDITIONAL_ISSUERS=http://localhost:30080/realms/iceberg
      - LAKEKEEPER__OPENID_AUDIENCE=lakekeeper
      - LAKEKEEPER__UI__OPENID_CLIENT_ID=lakekeeper
      - LAKEKEEPER__UI__OPENID_PROVIDER_URI=http://localhost:30080/realms/iceberg
      - RUST_LOG=info
    command: ["serve"]
    healthcheck:
      test: ["CMD", "/home/nonroot/lakekeeper", "healthcheck"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 3s
    depends_on:
      migrate:
        condition: service_completed_successfully
      shared-db:
        condition: service_healthy
      minio:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8181:8181"
    networks:
      - lakehouse-network

  migrate:
    image: ${LAKEKEEPER_TEST__SERVER_IMAGE:-quay.io/lakekeeper/catalog:latest-main}
    container_name: migrate
    pull_policy: always
    environment:
      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://lakekeeper_admin:lakekeeper_password@shared-db:5432/lakekeeper_db
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://lakekeeper_admin:lakekeeper_password@shared-db:5432/lakekeeper_db
      - LAKEKEEPER__AUTHZ_BACKEND=openfga
      - LAKEKEEPER__OPENFGA__ENDPOINT=http://openfga:8081
      - RUST_LOG=info
    restart: "no"
    entrypoint: ["/home/nonroot/lakekeeper", "migrate"]
    depends_on:
      shared-db:
        condition: service_healthy
      openfga:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      minio:
        condition: service_healthy
      mc:
        condition: service_completed_successfully
    networks:
      - lakehouse-network

  shared-db:
    image: postgres:16
    container_name: shared-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - shared-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres"]
      interval: 20s
      timeout: 20s
      retries: 2
      start_period: 10s
    ports:
      - 5432:5432
    networks:
      - lakehouse-network

  openfga-migrate:
    image: openfga/openfga:v1.8
    container_name: openfga-migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga_admin:openfga_password@shared-db:5432/openfga_db?sslmode=disable
    depends_on:
      shared-db:
        condition: service_healthy
    networks:
      - lakehouse-network

  openfga:
    image: openfga/openfga:v1.8
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://openfga_admin:openfga_password@shared-db:5432/openfga_db?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=50
      - OPENFGA_PLAYGROUND_ENABLED=false
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 5s
      timeout: 30s
      retries: 3
    depends_on:
      shared-db:
        condition: service_healthy
      openfga-migrate:
        condition: service_completed_successfully
    networks:
      - lakehouse-network

  lakekeeper-bootstrap:
    container_name: lakekeeper-bootstrap
    image: python:3.11-slim
    volumes:
      - ./bootstrap/bootstrap.py:/app/bootstrap.py # mount file local into container
    working_dir: /app
    command: >
      sh -c "pip install requests pyjwt &&
      python bootstrap.py"
    depends_on:
      keycloak:
        condition: service_healthy
      lakekeeper:
        condition: service_healthy
    restart: "no" # exit when complete
    networks:
      - lakehouse-network

  create-warehouse:
    container_name: create-warehouse
    image: python:3.11-slim
    volumes:
      - ./create-warehouse/create-warehouse.py:/app/create-warehouse.py # mount file local into container
    working_dir: /app
    command: >
      sh -c "pip install boto3 requests &&
      python create-warehouse.py"
    depends_on:
      lakekeeper:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: "no" # exit when complete
    networks:
      - lakehouse-network

volumes:
  shared-db-data:
  minio-data:

networks:
  lakehouse-network:
    name: lakehouse-network
    driver: bridge
